services:
  perceptio:
    container_name: perceptio
    build: .
    environment:
      MIX_ENV: prod
      PHX_HOST: localhost
      PORT: 4000
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - '80:4000'