import Config
# Configure your database
config :perceptio, Perceptio.Repo,
  adapter: Ecto.Adapters.Tds,
  username: System.get_env("DB_USERNAME"),
  password: System.get_env("DB_PASSWORD"),
  hostname: System.get_env("DB_HOSTNAME"),
  port: String.to_integer(System.get_env("DB_PORT") || "1433"),
  database: System.get_env("DB_NAME"),
  show_sensitive_data_on_connection_error: false,
  pool_size: 10
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.

#host = System.get_env("PHX_HOST") || "example.com"
port = String.to_integer(System.get_env("PORT") || "4000")

#config :perceptio, :dns_cluster_query, System.get_env("DNS_CLUSTER_QUERY")

config :perceptio, PerceptioWeb.Endpoint,
  #url: [host: host, port: 443, scheme: "https"],
  # http: [
  #   # Enable IPv6 and bind on all interfaces.
  #   # Set it to  {0, 0, 0, 0, 0, 0, 0, 1} for local network only access.
  #   # See the documentation on https://hexdocs.pm/bandit/Bandit.html#t:options/0
  #   # for details about using IPv6 vs IPv4 and loopback vs public addresses.
  #   ip: {0, 0, 0, 0, 0, 0, 0, 0},
  #   port: port
  # ],
  http: [ip: {0,0,0,0}, port: port],
  check_origin: false,
  cache_static_manifest: "priv/static/cache_manifest.json"


# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Perceptio.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
